### Hindu Astrology Prediction

Hindu astrology (also known as Vedic astrology or Jyotish) is a highly systematic form of astrology and could serve as a suitable starting point for developing a machine learning model. This approach may be more structured than Western astrology, as it heavily relies on precise mathematical calculations and a clear set of rules based on planetary positions, houses, and nakshatras (lunar mansions).

First explore using machine learning models for Vedic astrology (Hindu astrology) or another system that may be simpler to process than Western astrology. By leveraging structured data from planetary positions, Nakshatras (lunar mansions), and Dasha systems, you could create prediction models or analysis tools. This could offer a unique approach to astrology using machine learning before taking on more complex systems like Western astrology.
Machine Learning for Hindu Astrology:

In [ ]:
import requests
from bs4 import BeautifulSoup

namess = []

headers = {
    'User-Agent': (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"
    )
}

data = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
# data = list("A")
all_names = {}
# names_href = []
for i in data:
    names_href = []
    base_url = f"https://www.astro.com/wiki/astro-databank/index.php?title=Special:AllPages&from={i}"

    response = requests.get(base_url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')

    letter_links = soup.find_all("div", class_="mw-allpages-body")

    for div in letter_links:
        for a_tag in div.find_all("a"):
            clean_name = a_tag.text.strip()
            print(clean_name)
            names_href.append(clean_name)
    all_names[str(i)] = names_href

Streaming output truncated to the last 5000 lines.
Labruyere, Cornelia
Labruyère, Cornelia
Labry, Pierre
Labyorteaux, Ron
Labys, Jane
Labèque, Katia
Labèque, Marielle
Lacalle, Luis Alberto
Lacan, Alfred
Lacan, Caroline
Lacan, Jacques
Lacan, Judith
Lacan, Madeleine
Lacan, Marc
Lacan, Sibylle
Lacan, Thibault
Lacarrau, Marie-Sophie
Lacassagne, Alexandre
Lacassagne, Antoine
Lacassin, Francis
Lacaton, Anne-Marie
Lacavalerie, Marco Antonio
Lacaze, Claude
Lacaze, Marie-Jean-Lucien
Lacaze-Duthiers, Henri de
Lacazette, Alexandre
Lacen, Sonia
Lacerda, Allan
Lacerda, Carlos
Lacerda, Hilton
Lacerte, René
Lacey, Alan
Lacey, F.W.
Lacey, Robert
Lachaud, Charles
Lacheau, Philippe
Lachelier, Jules
Lacheroy, Annie
Lacheroy, Charles
Lachey, Brooklyn
Lachey, Camden
Lachey, Drew
Lachey, Nick
Lachheb, Khalid
Lachheb, Taoufik
Lachieze-Rey, Marc
Lachièze-Rey, Marc
Lachmann, Henri
Lachmann, Ludwig
Lachmann, Robert
Lachmann, Vera
Lachowsky, William Craig
Lackey, John
Lackey, Masako
Lackey, Mercedes
Laclotte, Michel
Lacombe, Bernard
Lacombe, Georges
Lacombe, Georges (1902)
Lacombe, Guy
Lacombe, Henri
Lacombe, Louis
Lacombe, Michel
Lacombe, Olivier
Lacombe, Paul
Lacombe Olivier
Lacome d'Estalenx, Paul
Laconi, Regis
Laconi, Régis
Lacordaire, Jean-Baptiste
Lacoste, Catherine
Lacoste, Marie
Lacoste, Pierre
Lacoste, Rene
Lacoste, René (le crocodile)
Lacoste, Robert
Lacoste, Vincent
Lacotte, Pierre
Lacoue-Labarthe, Philippe
Lacour, José André
Lacour, Laurence
Lacourt, Camille
Lacouture, Jean
Lacquet, Albert
Lacrampe, Andre
Lacrampe, André
Lacroix, Alfred
Lacroix, Christian
Lacroix, Jean
Lacroix, Jean-Pierre
Lacroix, Léo
Lacroix, Michel
Lacroix, Paul
Lacroix, Philippe
Lacroix, Pierre
Lacrouze, Marius
Lacuria, Paul-François-Gaspard
Lacy, Allen
Lacy, Creighton
Lacy, Jerry
Lacy, Sarah
Lacôme, Paul
Ladd, Alan
Ladd, Alan Jr.
Ladd, Alana
Ladd, Andrew
Ladd, David
Ladd, David Alan
Ladd, Diane
Ladd, Jordan
Ladd, Marjorie
Ladd, Midge
Ladenburg, Rudolf
Ladesou, Chantal
Ladislaus Luitpold, Archduke of Austria
Ladislaus Philipp, Archduke of Austria
Ladjadj, Stephane
Ladjadj, Stéphane
Ladmiral, Nicole
Ladmirault, Paul Emile
Ladner, Richard E.
Ladoumegue, Jules
Ladreit de Lacharriere, Marc
Ladreit de Lacharrière, Marc
Ladstatter, Konrad
Lady Chablis
Lady Gaga
Lady Leshurr
Lady London
Lady Sovereign
Ladymon, Horace
Ladègaillerie, Jacques
Lae, Erling
Laemmle, Carl
Laennec, Rene
Laennec, Rene T.H.
Laennec, René
Laettner, Christian
Lafaille, Jean-Christophe
Lafargue, Quentin
Lafay, Bernard
Lafayette
Lafayette, Andrée
Lafer Piva, Horácio
Laferriere, Adolphe
Laferrière, Adolphe
Lafesse, Jean-Yves
Lafferre, Louis
Laffin, Dominique
Laffite, Jacques
Laffite, Margot
Laffitte, Charles
Laffitte, Pierre
Laffoley, Paul
Laffon, Emile
Laffon, Rafael
Laffon, Yolande
Laffon, Émile
Laffon de Ladebat, Andre Emile Leon
Laffon de Ladebat, André Émile Léon
Laffont, Jean-Jacques
Laffont, Patrice
Laffont, Perrine
Laffont, Robert
Lafforgue, Ingrid
Lafforgue, Laurent
Lafforgue, Rene-Louis
Lafforgue, René-Louis
Lafitte, Guy
Lafitte, Laurent
M'Barali, Claude
M'Vila, Yann
M'barali, Claude
M.Leiris, Hélène
M. Pokora
MB14
MC Loma
MC Solaar
MC Souleye
MHD (rapper)
MUA, Manny
M Lamar
M`barali, Claude
Ma'at-Ra, Djehuty
Ma, Anandamayi
Ma Anand Sheela
Maar, Dora
Maartens, Maarten
Maartmann-Moe, Kjell
Maas, Alex
Maas, Paul
Maass, Hermann
Maazel, Lorin
Maaß, Hermann
Mabel
Mabille, Bernard
Mabotja, Relebogile
Mac-Avoy, Édouard Georges
Mac-Mahon, Patrice Maurice
MacAdams, Lewis
MacAdams, Lewis Perry
MacAlister, Robert Carter
MacArthur, Arthur IV
MacArthur, Douglas
MacArthur, Edith
MacArthur, Ellen
MacArthur, Jean
MacArthur, Mary
MacAulay, Fred
MacBeath, Mhairi Isabel
MacBeth, George
MacBeth, George Mann
MacBride, Sean
MacBride, Seán
MacBtide, Sean
MacCaig, Norman
MacCallum, Cather
MacColl, Dugald
MacColl, Kirsty
MacCorkindale, Simon
MacCormick, Donald
MacCraig, Hugh
MacCunn, Hamish
MacDiarmid, Hugh
MacDonald, Ann-Marie
MacDonald, Brendan
MacDonald, Calum
MacDonald, George
MacDonald, James
MacDonald, Jeanette
MacDonald, Jeffrey
MacDonald, John
MacDonald, John A.
MacDonald, John D.
MacDonald, Malcolm
MacDonald, Margo
MacDonald, Michael
MacDonald, Mora
MacDonald, Ramsay
MacDonald, Ramsey
MacDonald, Rory
MacDonald, Virginia B.
MacDougall, James Dunlop
MacDowell, Andie
MacElvoy, Carol
MacFadden, Bernard
MacFarlane, Marianne
MacGillivray, Donald
MacGillivray, Ian
MacGillivray, James P.
MacGraw, Ali
MacGregor, Elizabeth Ann
MacGregor, Geddes
MacGregor, Ian
MacGregor, Jimmie
MacGregor, John
MacGregor, Katherine
MacGregor, Trish
MacInnes, Helen
MacInnes, Inez C.
MacInnes, William
MacIssac, Ashley
MacIvor, Daniel
MacKay, Donald
MacKay, Fulton
MacKay, James Peter
MacKay, Susan
MacKenzie, Compton
MacKenzie, Eddie
MacKenzie, Edwina
MacKenzie, Gisele
MacKenzie, Lewis W.
MacKenzie, Scott
MacKinnell, Terry
MacKinnon, Catharine
MacKinnon, Donald MacKenzie
MacKinnon, Roderick
MacLachlan, Kyle
MacLaine, Shirley
MacLane, Barton
MacLean, Alistair
MacLean, David John
MacLean, Don
MacLean, Donald D.
MacLean, Jack
MacLean, Sarah
MacLean, Sorley
MacLean, Tara
MacLean, W. J.
MacLeary, Donald
MacLeish, Eric
MacLennan, Hugh
MacLennan, Robert
MacLeod, Ally
MacLeod, Bridget
MacLeod, Donny
MacLeod, Gavin
MacLeod, George
MacLeod, John
MacLeod, John (1876)
MacLeod, John (1937)
MacLeod, John J.
MacLiammoir, Michael
MacLusky, Hector
MacMartin, John
MacMath, Zac
MacMillan, Harold
MacMillan, Kenneth
MacMillan, Robert
MacMillan, Sir Kenneth
MacNaughtan, Alan
MacNaughton, Alan
MacNeil, Cornell
MacNeil, Cornell Hill
MacNeil, Karen
MacNeil, Mick
MacNeil, Wade
MacPhail, Bill
MacPhail, Ian
MacPhail, William C.
MacPherson, James
MacQueen, William
MacRae, Duncan
MacRae, Gordon
MacRae, Heather
MacRobert, Thomas Murray
MacTaggart, Andrew
MacTaggart, William
Mac Kac
Macaigne, Pierre
Macaire, Guillaume
Macaire, Lionel
Macanico, Antonio
Macario, Erminio
Macary, Michel
Macci, Rick
Maccione, Aldo
Macdonald, Andy
Macdonald, George
Macdonald, Hamish
Macdonald, John A.
Macdonald, Ross
Macdonald, Sir George
Mace, Jean
Mace-Archer-Mills, Thomas
Mace de Lepinay, Francois
Macedo, Bispo Edir
Macedo, Marcos
Macedo, Wirley
Macedo Cima, Robinson
Macha, Mike
Machado, Antonio
Machado, António Ginestal
Machado, Campos
Machado, Felipe
Machado, Manuel
Machado Ruiz, Cupriana
Machajewski, John
Machalski, Andrzej
Machholz, Donald
Machiavelli, Niccolo
Machiavelli, Niccolò
Machin, Alfred
Machin, Marc
Machine Gun Kelly
Machiz, Leon
Macho, Fritz
Macht, Gabriel
Macias, Enrico
Maciel, Marco
Mack, Connie
Mack, Deedee
Mack, Jillie
Mack, John E.
Mack, John J.
Mack, John J. (1944)
Mack, Ludwig Hirschfeld
Mack, Natasha
Mack, Sam
Mack, Thomas L.
Mack John E. (1934)
Mackampa, Jordan
Mackay, Aeneas
Mackay, Alastair
Mackay, Barry
Mackay, John Henry
Mackay, Megan
Mackaye, Ian
Macke, August
Macke, Kenneth A.
Mackellar, Dorothea
Mackensen, Eberhard von
Mackenzie, Alexander
Mackenzie, Billy
Mackenzie, Gordon
Mackenzie, Hugh Stirling
Mackenzie, James
Mackenzie, Sir Hugh Stirling
Mackerras, Alastair
Mackerras, Charles
Mackey, Dee
Mackey, Emma
Mackie, Bob
Mackie, Peter
Mackiernan, Douglas
Mackiewicz, Tomasz
Mackin, Alan Richard
Mackin, James S.
Mackintosh, Angus Mackay
Mackintosh, Cameron
Mackintosh, Charles
Mackintosh, Charles Rennie
Mackintosh, Sir Angus Mackay
Macklemore
Mackness, Tracy
Maclay, Joseph
Maclean, John
Macleod, Anna
Maclin, Corey
Macnee, Patrick
Macola, Beatrice
Macomber, Leanne
Macpherson, Elle
Macpherson, Greg
Macquet, Michel
Macrelli, David
Macri, Mauricio
Macris, Vanderlei
Macron, Brigitte
Macron, Emmanuel
Macy, Bill
Macy, William H.
Macy Kate
Macé, Jean
Macé-Scaron, Joseph
Macé de Lépinay, François
Macêdo, Maria Cláudia
Madamet, Nicolas
Madani, Hussain Ahmad
Madd, Pierrette
Madden, Harlow
Madden, John
Madden, Raddix
Madden, Richard
Madden, Sparrow
Madden, Sparrow James
Maddern, Clarence
Maddi, Yayia
Maddie, Ginette
Maddow, Rachel
Maddux, Greg
Maddux, Sam Jr.
Madec, Joseph
Madec, Roger
Madej, Donka
Madel, William David
Madeleine, Bernard
Madeleine, Princess
Madeleine, Princess of Sweden
Madelenat, Patrick
Madelin, Alain
Mademoiselle Mante
Mademoiselle Nathalie
Madeon
Madeon (French dj)
Mader, Jean-Pierre
Mader, Malu
Maderna, Bruno
Madero, Francisco I.
Madero, Gustavo A.
Madersperger, Josef
Madersperger, Joseph
Madia, Giorgio
Madinier, Bruno
Madiol, Arnold J.
Madiot, Marc
Madiot, Yvon
Madison, Dolley
Madison, Guy
Madison, Holly
Madison, James
Madison, Martha
Madison, Mikey
Madix, Ariana
Madoff, Bernard
Madoff, Bernie
Madole, Howard
Madolell Estévez, Joaquín
Madonna
Madrid, Delly
Madrid Hurtado, Miguel De La
Madrigal Nieto, Rodrigo
Madsen, Brigham D.
Madsen, Jeff
Madsen, Peter
Madsen, Steinar
Madsen, Virginia
Madsen, Wayne
Madssen, Ada
Madureira, Antúlio
Maduro, Nicolas
Madys, Marguerite
Madénian, Mathieu
Maeght, Aime
Maeght, Aimé
Maene, Stefaan
Maenza, Vincenzo
Maenzel, Kurt
Maerli, Terje
Maertens, Freddy
Maertens, Willy
Maes, Romain
Maes, Sylvère
Maester
Maestrelli, Tommaso
N'Dour, Youssou
NDiaye, Marie
Nabarro, Gerald
Naber, Johanna
Naber, John
Nabokov, Vladimir
Nabors, Jim
Nabrit, James III
Nabuco, Joaquim
Naccherino, Michelangelo
Nachman of Breslov
Nacho Picasso
Nachtergaele, Matheus
Nachtigall, Gustav
Nada
Nadal, Ivana
Nadal, Rafael
Nadal, Rafael (junior)
Nadal, Rafael Jr.
Nadar
Nadaud, Gustave
Nadaud, Gustave Charlesn
Nadeau, Amanda
Nadeau, Claire
Nadeau, Maurice
Nadeem, Roha
Nader, George
Nader, Ralph
Nadezhda, Princess of Bulgaria
Nadi, Nedo
Nadiya
Nadolny, Stephanie
Naert, Joseph
Naess, Arne
Naess, Kate
Naess, Knut
Naess, Kristine
Naess, Petter
Naess, Ross
Naessens, Gaston
Naeye, Robert
Naftali, Peretz
Nagako, Empress of Japan
Nagami, Ishiro
Nagarjuna, Akkineni
Nagasu, Mirai
Nagel, Hanna
Nagel, Otto
Nagel, Willibald
Nagell-Erichsen, Einar
Nagell-Erichsen, Tinius
Nagell-Erichsen, Wibecke
Nagelmackers, Georges
Nagelsen, Betsy
Nagelson, Russ
Nagiev, Dmirty Vladimirovich
Nagle, David R.
Nagle, Duda
Nagrath, Anil
Nagui
Nagy, Charles
Nagy, Imre
Nagy, Scott
Nahim
Nahles, Andrea
Nahum, Bertin
Naibod, Valentine
Naidoo, Xavier
Naidu, Edwin
Naifeh, Marion
Naipaul, V. S.
Nair, Kesavan
Naise, Indy
Naismith, James
Naisse, Claude Alain
Najar, Nate
Najarian, John
Najim, Guzin
Najimy, Kathy
Najm, Khristu
Nakache, Alfred
Nakache, Armand
Nakache, Géraldine
Nakache, Olivier
Nakai, R. Carlos
Nakano, Lane
Nakasone, Yasuhiro
Nakazono, Mashiro
Naked Cowboy
Nakens, Jose
Nakens, José
Nakkachdji, Xavier
Nalan, Akrep
Nalbandian, Maggie
Naldi, Neda
Naldinho
Nalkowska, Zofia
Nallard, Louis
Nallaseth, Freny F.
Nallet, Jean-Claude
Nallon, Steve
Nally, Henry
Namath, Joe
Namias, Robert
Nance, Jack
Nancy, Jean-Luc
Nandino, Elías
Nanini, Marco
Nanjappa, Rani
Nannen, Henri
Nannini, Alessandro
Nannini, Danilo
Nannini, Gianna
Nano, Agnese
Nansen, Fridtjof
Nantes, Georges de
Nanty, Gerard
Nanty, Gérard
Nanty, Isabelle
Nao
Naouri, Jean-Charles
Naouri, Laurent
Napias, Henri
Napier, Bryce
Napieralski, Grzegorz
Napieras, Christian
Napierkowska, Stacia
Napoleon, Victor
Napoleon III
Napoli, Jean-Claude
Napolitano, Giorgio
Napolitano, Umberto
Napoléon, Victor
Napoléon III
Naquet, Robert
Naquet-Laroque, Raymond Elie
Naquet-Laroque, Raymond Élie
Narasimhaswami, B. V.
Narayan, Jaya Prakash
Narayananda, Swami
Narcejac, Thomas
Nardal, Paulette
Nardi, Bruno
Nardi, Marie-Ange
Nardini, Daniela
Nardo, Don
Nardone, Mario
Nargeolet, Paul-Henri
Narlay, Raymond
Narmon, François
Naroditsky, Daniel
Naruhito, Emperor of Japan
Naruhito, Prince of Japan
Narutowicz, Gabriel
Naschy, Paul
Nascimento, Celeste
Nascimento, Edson Cholbi
Nascimento, Fabíula
Nascimento, Gilberto
Nascimento, Jeniffer
Nascimento, Joshua
Nascimento, Kelly Cristina
Nascimento, Kely Christina
Nascimento, Milton
Nascimento, Sandra
Nash, Adam
Nash, Art
Nash, Bob
Nash, Brenda
Nash, Frederic Ogden
Nash, Graham
Nash, Grete
Nash, Jay Robert
Nash, John
Nash, John Henry
Nash, Leroy
Nash, Niecy
Nash, Philleo
Nash, Steve
Nasic, Sandra
Nasil, Maurice
Nasmyth, James
Nason, Elias
Nasri, Samir
Nasrullah Khan, Emir of Afghanistan
Nasse, Dietrich
Nasser, Abdal Gamal
Nasser, Gamal Abdel
Nassiet, Henri
Nassif, Paul
Nastase, Ilie
Nastasi, Alexander
Nasyrov, Murat Ismailovich
Nat, Marie-José
Nat, Marie José
Nat, Yves
Nataf, J. P.
Natalia
Natalia Alexeievna, Grand Duchess of Russia
Natalia Petrovna, Grand Duchess of Russia
Natalya Alexeyevna, Grand Duchess of Russia
Natanek, Piotr
Natanson, Jacques
Nathalie
Nathan
Nathan, Leonard
Nathan, Leonard Edward
Nathan-Garamond, Jacques
Nathaniel Waterman
Nathans, Daniel
Nation, Carry
Nation:Belgium
Nation:China:revolution conj. Jup-Nep
Nation:Federal Republic of Germany
Nation:France:Revolution Conjunction Jup-Ura
Nation:German Democratic Republic (DDR)
Nation:Greece:Independance Conjunctions
Nation:Greece:Proclamation and End of Monarchy
Nation:Portugal:Proclamation of Republic (1910)
Nation:Switzerland:Jupiter-Uranus
Nation:Switzerland 1848
Nation: Afghanistan
Nation: Afghanistan Taliban Rule (1996)
Nation: Arabia
Nation: Australia (British Colonisation)
Nation: Australia (Commonwealth)
Nation: Australia (Inauguration)
Nation: Austria (2nd Republic)
Nation: Belgium
Nation: Brazil
Nation: Brazil (Empire, Independence)
Nation: Brazil (Independence)
Nation: Brazil (Republic)
Nation: Brazil Independence
Nation: Brazil discovery
Nation: Dominion of India
Nation: Dominion of Pakistan
Nation: East Timor
Nation: Egypt (Republic)
Nation: Federal Republic of Germany
Nation: France 1789:Revolution Conjunction Jup-Ura
Nation: Georgia (1918 Independence)
Nation: Georgia (1991 Independence)
Nation: German Democratic Republic (DDR)
Nation: German Reich (1871)
Nation: Germany, Weimar Republic (1918)
Nation: Germany (Reunification, 1990)
Nation: Greece:Proclamation and End of Monarchy
Nation: Greece 1821:Independence Conjunctions
Nation: India (Independence)
Nation: India (Republic)
Nation: Indonesia (Proclamation of Independence)
Nation: Iraq Hussein Regime
Nation: Israel
Nation: Kenya
Nation: Kingdom of Iraq
Nation: Kosovo
Nation: Lebanon
Nation: Montenegro
Nation: Pakistan (Independence)
Nation: Portugal:Proclamation of Republic (1910)
Nation: Portugal (Battle of Sao Mamede)
Nation: Portugal (Proclamation of Republic 1910)
Nation: Republic ofSouth Sudan
Nation: Republic of Iraq
Nation: Republic of South Sudan
Nation: Saudi Arabia
Nation: Second Polish Republic
Nation: Sri Lanka (Independence)
Nation: Sri Lanka (Republic)
Nation: Switzerland (1848 Federal Constitution)
Nation: Switzerland 1845:Jupiter-Uranus
Nation: Switzerland 1848
Nation: Taliban
Nation: Trinidad and Tobago
Nation: Turkey
Nation: Turkey (Republic)
Nation: USA No.1
Nation: USA No.10
Nation: USA No.11
Nation: USA No.12
Nation: USA No.13
Nation: USA No.14
Nation: USA No.15
Nation: USA No.15 (ratification)
Nation: USA No.2
Nation: USA No.3
Nation: USA No.4
Nation: USA No.5
Nation: USA No.6
Nation: USA No.7
Nation: USA No.8
Nation: USA No.9
Nation: USSR, foundation
Nation: Ukraine
Nation: Vatican City State
Nation: Venezuela
Nation: West Germany (Federal Republic, 1949)
Natorp, Paul
Natta, Alessandro
Natta, Giulio
Nature
Nature. Elazig earthquakes, Turkey
Nature:2015 Nepal earthquakes
Nature::Earthquake:Colombia 2004
Nature:Aegean Sea Earthquake 1905
Nature:Albstadt Earthquake 1978
Nature:Algarrobo Earthquake:Chile 1985
Nature:Ambato Earthquake:Ecuador 1949
Nature:Ancash Earthquake
Nature:Ancash Earthquake:Peru 1970
Nature:Anjar Earthquake:India 1956
Nature:April-May 2015 Nepal earthquake
Nature:Arica Earthquake and Tsunami:Chile 1868
Nature:Arica earthquake and tsunami
Nature:Aschabad Earthquake 1948
Nature:Basel Earthquake
Nature:Basilicata Earthquake 1857
Nature:Birth of Surtsey Volcano
Nature:Birth of Surtsey volcano
Nature:Buin Zahra Earthquake 1962
Nature:Cachar Earthquake:India 1984
Nature:Cairo Earthquake (1992)
Nature:Caldiran-Muradiye-Earthquake, 1976
Nature:Caracas Earthquake:Venezuela 1812
Nature:Casiguran Earthquake:Philippines 1968
Nature:Chalfant Valley earthquake 1986
Nature:Chios Earthquake 1881
Nature:Chios earthquake 1881
Nature:Cucuta Earthquake:Colombia/Venezuela
Nature:Dali Earthquake:China 1925
Nature:Dasht-e-Bayaz and Ferdows Earthquake
Nature:Dawu Earthquake:Sichuan 1981
Nature:Earthquake:Agadir
Nature:Earthquake:Alaska 1965
Nature:Earthquake:Anchorage 2018
Nature:Earthquake:Azores 1980
Nature:Earthquake:Bolivia 1994
Nature:Earthquake:Calabria 1638
Nature:Earthquake:California 1923 (offshore)
Nature:Earthquake:Caucasus
Nature:Earthquake:Central Asia
Nature:Earthquake:Central Asia 1992
Nature:Earthquake:Central California 1984
Nature:Earthquake:Central Italy 2016
O'Bannon, Charles
O'Bannon, Ed
O'Brian, Eddie Jr.
O'Brian, Hugh
O'Brien, Barry C.
O'Brien, Beckett
O'Brien, Conan
O'Brien, Dale
O'Brien, Dan
O'Brien, Dave
O'Brien, Dayton
O'Brien, Edna
O'Brien, George H. Jr.
O'Brien, Lorenzo
O'Brien, Michael
O'Brien, Michael J.
O'Brien, Olivia
O'Brien, Parry
O'Brien, Pat
O'Brien, Raymond F.
O'Brien, Shannon
O'Brien, Thomas J.
O'Brien, Virginia
O'Brien, William J.
O'Brien-Ely, Catalina
O'Bryan, Ronald Clark
O'Callaghan, Lloyd
O'Callaghan, Mike
O'Casey, Sean
O'Casey, Seán
O'Connell, Helen
O'Connell, Taaffe
O'Connell, William
O'Connor, Arden
O'Connor, Cameron
O'Connor, Cardinal John
O'Connor, Daniel
O'Connor, Daniel Emmett
O'Connor, Donald
O'Connor, James J.
O'Connor, Maureen
O'Connor, Pat
O'Connor, Renee
O'Connor, Robert Emmett
O'Connor, Sandra Day
O'Connor, Sinéad
O'Cull, Tesslynn
O'Day, Anita
O'Day, Aubrey
O'Dea, Pat
O'Dell, Tony
O'Donnell, Chelsea
O'Donnell, Daniel
O'Donnell, Lawrence
O'Donnell, Majella
O'Donnell, Peter
O'Donnell, Rosie
O'Donnell, Sean
O'Donnell, Shannon
O'Donnell, Vivienne Rose
O'Donoghue, Ben
O'Dowd, Kris
O'Dowd, Ryan
O'Gorman, Edmundo
O'Gorman, Juan
O'Grady, Brittany
O'Grady, Paul
O'Hair, Madalyn Murray
O'Hara, Daniel
O'Hara, Eureka
O'Hara, Frank
O'Hara, John
O'Hara, Maureen
O'Hara, Tom
O'Hare, Brian
O'Hare, Dean
O'Hare, Dean R.
O'Harris, Pixie
O'Hearn, Robert
O'Hurley, William Dylan
O'Keefe, John
O'Keeffe, Georgia
O'Kelly De Galway, Alberic
O'Leary, Brian
O'Leary, Michael
O'Leary, Nancy
O'Leary, Thomas H.
O'Loughlin, Herbert J.
O'Lovely, Olivia
O'Malley, Mike
O'Malley, Owen
O'Malley, Thomas
O'Meara, Mark
O'Neal, Arthur Daniel
O'Neal, Dick
O'Neal, Griffin
O'Neal, Jermaine
O'Neal, Mearah Sanaa
O'Neal, Patrick
O'Neal, Rebecca
O'Neal, Redmond
O'Neal, Ryan
O'Neal, Shaqir
O'Neal, Shaquille
O'Neal, Shareef
O'Neal, Tatum
O'Neil, Dave
O'Neil, Kevin W.
O'Neill, Aaron
O'Neill, Beverly
O'Neill, Brittany
O'Neill, C. William
O'Neill, Cherry Boone
O'Neill, Dion
O'Neill, Ed
O'Neill, Edward
O'Neill, Eugene
O'Neill, Evan
O'Neill, Jennifer
O'Neill, Joan
O'Neill, Joan (n:52401)
O'Neill, John J.
O'Neill, Liam
O'Neill, Liam Dunaway
O'Neill, Martin John
O'Neill, Patrick
O'Neill, Paul
O'Neill, Paul H.
O'Neill, Tip
O'Neill III, Thomas P.
O'Neill III, Thomas Philip
O'Nil, Suzette
O'Regan, Sean
O'Reilly, Anthony J.
O'Reilly, Bill
O'Reilly, Spencer
O'Reilly Schell, Lucy
O'Rel, Edward Allen
O'Riordan, Dolores
O'Rourke, Ryan
O'Sullivan, Edward William
O'Sullivan, Jacquie
O'Sullivan, Stephanie
O'Toole, Chelsea
O'Toole, Kathleen
O'Toole, Mark
O'Toole, Peter
O'Toole, Sparky
O' Keeffe, Georgia
O'connor, Denis
O. Henry
O`Brien, Dale
O`Brien, Parry
O`Callaghan, Mike
O`Connell, Helen
O`Connor, Daniel Emmett
O`Hara, John
O`Hara, Tom
O`Neal, Arthur Daniel
O`Neill, Joan
O`Neill, Thomas P. "Tip"
O`Toole, Peter
Oakes, Kirk Odean
Oakes, Randi
Oakie, Jack
Oakley, Annie
Oakley, Barbara
Oakley, Charles
Oakley, Robert B.
Oakley, Tyler
Oană, Ilie
Oates, John
Oates, Joyce Carol
Oates, Lawrence
Oates, Warren
Oatis, William N.
Obaldia, René de
Obama, Barack
Obama, Malia
Obama, Michelle
Obasi, Prince Emeka Jr.
Obendorf, Ralph L.
Oberg, Carl
Oberlin, J. F.
Oberling, Charles
Oberndorfer, Siegfried
Oberon, Merle
Obershaw, Brian
Obershaw, Mark
Oberst, Maximilian
Oberth, Hermann
Oberti, Daniel
Obey, Andre
Obey, André
Obispo, Pascal
Oblad, Alex Golden
Obledo, Mario
Oboussier, Robert
Obradovich, Dennis Lee
Obrecht, André
Obregon, Eugene A.
Obregon, Eugene Arnold
Obregon Loria, Rafael
Obregón, David
Obrochta, Connor
Obry, Hugues
Obst, Lynda
Ocampo, Ambeth
Ocampo, Victoria
Ocana, Luis
Ocariz, Fernando

In [68]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

headers = {
    'User-Agent': (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"
    )
}


# List to store extracted data
extracted_data = []

for i in all_names:

    for j in all_names[str(i)]:
        url = "https://www.astro.com/astro-databank/" + j.replace(' ', '_')
        print(f"Fetching: {url}")
        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            soup = BeautifulSoup(response.text, "html.parser")

            name_row = soup.find('b', string='Name')
            name = name_row.find_next('td').get_text(strip=True).split('Gender:')[0].strip() if name_row else None

            # Birthname
            birthname_row = soup.find('td', class_="metadata-label", string='Birthname')
            birthname = birthname_row.find_next('td').get_text(strip=True) if birthname_row else None

            # Gender
            gender_row = soup.find('a', title="Help:Gender")
            gender = gender_row.parent.get_text(strip=True).replace('Gender:', '').strip() if gender_row else None

            #  Date of Birth
            date_of_birth = soup.find('td', string='born on')
            date = date_of_birth.find_next('td').get_text(strip=True) if date_of_birth else None

            # Place of Birth
            place_of_birth = soup.find('td', string='Place')
            birth_place = place_of_birth.find_next('td').get_text(strip=True) if place_of_birth else None

            #  Timezone
            timezone_row = soup.find('a', title="Help:Timezone")
            timezone = timezone_row.find_next('td').get_text(strip=True) if timezone_row else None

            source_data = soup.find('a',title="Help:DataSource")
            source = source_data.parent.find_next('td').get_text(strip=True).split('Rodden')[0].strip() if source_data else None
            #Rating
            Ratingg = soup.find('a', title="Help:RR")
            Rating = Ratingg.find_next('b').get_text(strip=True) if Ratingg else None

            Collectorr = soup.find('a',title ="Help:Collector")
            Collect = Collectorr.find_next('a').get_text(strip=True) if Collectorr else None

            # Astrology data
            Astrology_data = soup.find('a', title="Help:Astro data")
            a_data = Astrology_data.find_next('td').get_text(strip=True) if Astrology_data else None
            # print(a_data)
            sun, moon, asc = None, None, None

            if a_data:
                data_parts = a_data.split("Asc.")

                if len(data_parts) == 2:
                    sun_moon = data_parts[0]
                    asc = data_parts[1].strip().rstrip("'")

                    if "'" in sun_moon:
                        sun, moon = sun_moon.split("'")
                        sun = sun.strip()
                        moon = moon.strip()

                # carrier
                list_items = soup.find_all("li")
                # print(list_items)
                found_vocation = False
                for text in list_items:
                    teexxt = text.get_text()
                    if "Vocation" in teexxt:
                        Vocation = teexxt.split(':')
                        if len(Vocation) > 1:
                            career = Vocation[1]
                        found_vocation = True
                        break
                if not found_vocation:
                    career = None

                extracted_data.append({
                    'Name': name,
                    'Birthname': birthname,
                    'Gender': gender,
                    'Date of Birth': date,
                    'Place of Birth': birth_place,
                    'Timezone': timezone,
                    'Data Source' : source,
                    'Rodden Rating' : Rating,
                    'Collector' : Collect,
                    'Sun Position' : sun,
                    'Moon Position' : moon,
                    'Asc pos' : asc,
                    "Career " : career
                })

            else:
                print(f"Failed to fetch data for {j}: {response.status_code}")

In [ ]:
print('kk')

kk

In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# importing dataset
df = pd.read_csv('dataset.csv')

In [3]:
# First five rows
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,15°48,24°32,Entertain/Music
1,A-Trak,Alain Macklovitch,M,30 March 1982 at 08:00(= 08:00 AM ),"Montréal, Quebec (CAN),45n31, 73w34",EST,Accuracy in question,C,Scholfield,09°30,17°29,03°57,Business
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,15°55,24°34,Entertain/Music
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,16°28,03°25,Writers
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,14°27,25°56,Business

In [4]:
# Last 5 rows
df.tail()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career
8363,"Zins, Lucien",Lucien Zins,M,14 September 1922 at 22:30(= 10:30 PM ),"Troyes, France,48n18, 4e05",GDT h1e (is daylight saving time),Quoted BC/BR,AA,Steinbrecher,21°16,26°52,19°03,Sports
8364,"Zinser, Bodo",NaN,M,8 November 1947 at 22:26(= 10:26 PM ),"Karlsruhe, Germany,49n03, 8e24",MET h1e (is standard time),From memory,A,Taeger,15°38,26°59,07°19,Computer
8365,"Zinzendorf, Karl von",K. v. Z. und Pottendorf,M,5 January 1739 at 20:30(= 8:30 PM ),"Dresden, Germany,51n03, 13e44",LMT m13e44 (is local mean time),Bio/autobiography,B,Scholfield,15°08,20°31,03°26,Politics
8366,"Zinzendorf, Ludwig von",Ludwig Friedrich Julius Graf von Z.,M,23 September 1721 at 20:00(= 8:00 PM ),"Nuremberg, Germany,49n27, 11e04",LMT m11e04 (is local mean time),From memory,A,Scholfield,00°36,28°40,00°12,NaN
8367,"Zinzendorf, Nicolaus",Nikolaus Ludwig von Zinzendorf und Pottendorf,M,26 May 1700 (greg.) at 18:00(= 6:00 PM ),"Dresden, Germany,51n03, 13e44",LMT m13e44 (is local mean time),Quoted BC/BR,AA,Müller,05°17,21°06,15°17,Politics

In [5]:
# Number of columns and rows of dataset
df.shape

(8368, 13)

In [6]:
# Dropping the duplicated dataset and changing in same dataset
df.drop_duplicates(inplace=True)

In [7]:
# new number of columns and rows
df.shape

(7799, 13)

In [8]:
# Extracting the best timezone
df['Timezone'] = df['Timezone'].apply(lambda x: x.split(' ')[0] if isinstance(x, str) else x)

In [9]:
# datatype of all columns
df.dtypes

Name              object
Birthname         object
Gender            object
Date of Birth     object
Place of Birth    object
Timezone          object
Data Source       object
Rodden Rating     object
Collector         object
Sun Position      object
Moon Position     object
Asc pos           object
Career            object
dtype: object

In [10]:
# splitting the place of birth as they contain birth place and latitude and longitude
split_data = df['Place of Birth'].str.split(',', expand=True)
# print(split_data[0]+','+split_data[1])

In [11]:
# New column as Birth Place from Place of Birth
df['Birth Place'] = split_data[0].str.strip() + ' ' + split_data[1].str.strip()

In [12]:
# latitude longitude
df['lat_lon'] = split_data[2].str.strip() + ', ' + split_data[3].str.strip()

In [13]:
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career,Birth Place,lat_lon
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,15°48,24°32,Entertain/Music,Provins France,"48n33, 3e18"
1,A-Trak,Alain Macklovitch,M,30 March 1982 at 08:00(= 08:00 AM ),"Montréal, Quebec (CAN),45n31, 73w34",EST,Accuracy in question,C,Scholfield,09°30,17°29,03°57,Business,Montréal Quebec (CAN),"45n31, 73w34"
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,15°55,24°34,Entertain/Music,Lima Peru,"12s03, 77w03"
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,16°28,03°25,Writers,Tours France,"47n23, 0e41"
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,14°27,25°56,Business,Bryn Mawr (Delaware County) Pennsylvania,"40n0116, 75w1901"

In [14]:
# Null values
df.isnull().sum()

Name                 0
Birthname         3239
Gender             581
Date of Birth        0
Place of Birth       0
Timezone             0
Data Source          0
Rodden Rating        0
Collector            0
Sun Position       319
Moon Position      319
Asc pos            319
Career            1135
Birth Place          0
lat_lon              0
dtype: int64

In [15]:
# Extracting latitude and longitude
df['get_latitude'] = df['lat_lon'].apply(lambda x: x.split(',')[0] if isinstance(x, str) else x)
df['get_longitude'] = df['lat_lon'].apply(lambda x: x.split(',')[1] if isinstance(x, str) else x)

In [16]:
#48n33 48n0  48n3207 40n0116
# converting latitude to decimal
import re

def convert_to_decimal(lat):
    match = re.match(r"(\d+)[nNsS](\d{1,2})(\d{2})?", lat)

    if match:
        degrees = match.group(1)
        if match.group(3):
            minutes = match.group(2) + match.group(3)
        else:
            minutes = match.group(2)

        decimal_degrees = float(degrees) + float(minutes) / 60
        if 's' in lat.lower():
            decimal_degrees = -decimal_degrees
        return round(decimal_degrees, 2)
    else:
        return None

# 40n0116 48n33
# get latitude
df['latitude'] = df['get_latitude'].apply(convert_to_decimal)

In [17]:
# Removing all rows where latitude is less than -90 and greater than 90
def lat(row):
  return -90 <= row <= 90
df = df[df['latitude'].apply(lat)]

In [18]:
# convert longitude to decimal
def convert_to_decimal(long):
    try:
        match = re.match(r"(\d+)([eEwW])(\d{1,2})?(\d{2})?", long)
        if match:
            degrees = match.group(1)
            direction = match.group(2).lower()
            minutes = match.group(3) if match.group(3) else "0"
            if match.group(4):
                minutes += match.group(4)

            decimal_degrees = float(degrees) + float(minutes) / 60
            if direction == 'w':
                decimal_degrees = -decimal_degrees
            return round(decimal_degrees, 2)
        else:
            return None
    except ValueError:
        return None

# get longitude
df['longitude'] = df['get_longitude'].str.strip().apply(convert_to_decimal)

In [19]:
# removing all rows where longitude value less than -180 and greater than 190
def longg(row):
  return -180 <= row <= 180
df = df[df['longitude'].apply(longg)]

In [20]:
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career,Birth Place,lat_lon,get_latitude,get_longitude,latitude,longitude
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,15°48,24°32,Entertain/Music,Provins France,"48n33, 3e18",48n33,3e18,48.55,3.30
1,A-Trak,Alain Macklovitch,M,30 March 1982 at 08:00(= 08:00 AM ),"Montréal, Quebec (CAN),45n31, 73w34",EST,Accuracy in question,C,Scholfield,09°30,17°29,03°57,Business,Montréal Quebec (CAN),"45n31, 73w34",45n31,73w34,45.52,-73.57
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,15°55,24°34,Entertain/Music,Lima Peru,"12s03, 77w03",12s03,77w03,-12.05,-77.05
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,16°28,03°25,Writers,Tours France,"47n23, 0e41",47n23,0e41,47.38,0.68
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,14°27,25°56,Business,Bryn Mawr (Delaware County) Pennsylvania,"40n0116, 75w1901",40n0116,75w1901,41.93,-106.68

In [21]:
# splitting Date of Birth to get birth date and birth time as separate columns
split_part = df['Date of Birth'].str.split(' ', expand=True)
split_part

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,6,October,1968,at,17:35(=,5:35,PM,),None,None,None,None,None
1,30,March,1982,at,08:00(=,08:00,AM,),None,None,None,None,None
2,30,May,1986,at,21:02(=,9:02,PM,),None,None,None,None,None
3,19,December,1947,at,20:00(=,8:00,PM,),None,None,None,None,None
4,28,September,1971,at,08:45(=,08:45,AM,),None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8363,14,September,1922,at,22:30(=,10:30,PM,),None,None,None,None,None
8364,8,November,1947,at,22:26(=,10:26,PM,),None,None,None,None,None
8365,5,January,1739,at,20:30(=,8:30,PM,),None,None,None,None,None
8366,23,September,1721,at,20:00(=,8:00,PM,),None,None,None,None,None
8367,26,May,1700,(greg.),at,18:00(=,6:00,PM,),None,None,None,None

In [22]:
# Adding new columns as Birth Date and Birth Time
df['Birth Date'] = split_part[0] + ' ' + split_part[1]+ ' ' +split_part[2]
df['Birth Time']  = split_part[4].str.slice_replace(-2,None,"")

In [23]:
df['Birth Time'] = df['Birth Time'].apply(lambda x: x if x is not None and len(x) == 5 and x[2] == ':' and x[:2].isdigit() and x[3:].isdigit() else None)

In [24]:
# All columns
df.columns

Index(['Name', 'Birthname', 'Gender', 'Date of Birth', 'Place of Birth',
       'Timezone', 'Data Source', 'Rodden Rating', 'Collector', 'Sun Position',
       'Moon Position', 'Asc pos', 'Career ', 'Birth Place', 'lat_lon',
       'get_latitude', 'get_longitude', 'latitude', 'longitude', 'Birth Date',
       'Birth Time'],
      dtype='object')

In [25]:
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,...,Asc pos,Career,Birth Place,lat_lon,get_latitude,get_longitude,latitude,longitude,Birth Date,Birth Time
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,...,24°32,Entertain/Music,Provins France,"48n33, 3e18",48n33,3e18,48.55,3.30,6 October 1968,17:35
1,A-Trak,Alain Macklovitch,M,30 March 1982 at 08:00(= 08:00 AM ),"Montréal, Quebec (CAN),45n31, 73w34",EST,Accuracy in question,C,Scholfield,09°30,...,03°57,Business,Montréal Quebec (CAN),"45n31, 73w34",45n31,73w34,45.52,-73.57,30 March 1982,08:00
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,...,24°34,Entertain/Music,Lima Peru,"12s03, 77w03",12s03,77w03,-12.05,-77.05,30 May 1986,21:02
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,...,03°25,Writers,Tours France,"47n23, 0e41",47n23,0e41,47.38,0.68,19 December 1947,20:00
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,...,25°56,Business,Bryn Mawr (Delaware County) Pennsylvania,"40n0116, 75w1901",40n0116,75w1901,41.93,-106.68,28 September 1971,08:45

In [26]:
# Get value Counts
df['Rodden Rating'].value_counts()

Rodden Rating
AA     4430
A      1853
C       548
B       318
X       299
DD       69
XX       17
AAX       5
AX        5
Name: count, dtype: int64

In [27]:
# To enhance prediction accuracy, remove all rows except those with 'AA', 'A' and 'B' ratings, as advised by the website for better predictive performance.
df = df[df['Rodden Rating'].isin(['AA', 'A','B'])]

In [28]:
# new number of columns
df.shape

(6601, 21)

In [29]:
# Retrieve unique values from the 'Gender' column to understand the different categories present in the dataset
df['Gender'].unique()

array(['M', 'F', nan, 'Mix', 'MF', 'UNK', 'FM', 'Unk'], dtype=object)

In [30]:
df['Gender'].value_counts()

Gender
M      4597
F      1441
Mix      33
MF       11
UNK       4
FM        2
Unk       1
Name: count, dtype: int64

In [31]:
df.isnull().sum()

Name                 0
Birthname         2671
Gender             512
Date of Birth        0
Place of Birth       0
Timezone             0
Data Source          0
Rodden Rating        0
Collector            0
Sun Position         2
Moon Position        2
Asc pos              2
Career             990
Birth Place          0
lat_lon              0
get_latitude         0
get_longitude        0
latitude             0
longitude            0
Birth Date           0
Birth Time          98
dtype: int64

In [32]:
# Remove rows with null 'Gender' as they represent irrelevant real-life events
df = df[df['Gender'].notnull()]

In [33]:
# new shape after removing null values of gender
df.shape

(6089, 21)

In [34]:
# unique values of timezone
df['Timezone'].unique()

array(['MET', '-05', 'EDT', 'EST', 'PWT', 'LMT', 'CET', 'GMT', 'LST',
       'CEST', 'PDT', 'EWT', 'CST', 'GDT', 'EET', 'PST', 'WEMT', 'MEDT',
       'AST', 'IST', 'MST', 'HST', 'CDT', 'AWST', 'R4T', 'PMT', 'CWT',
       'BZT', '-03', 'AHST', 'MMT', 'WEST', 'BST', 'KST', 'NZT', 'WET',
       'MDT', 'SMT', 'MWT', 'SJMT', 'AEST', 'BMT', 'ADT', 'GDWT', 'R3T',
       'RMT', 'CMT', 'GET', '+04', 'EEST', 'AEDT', '+00', 'DMT', 'EEDT',
       'BZDT', '-02', 'h5w', 'GST', 'MSK', 'NFT', '-04', 'NST', 'ACST',
       'AMT', 'EAT', 'NZST', '-10', 'SST', 'JST', 'SAST', 'ONZT', 'EPT',
       'BDST', '+07', '+072', 'IDT', 'R11S', '+05', 'VET', 'FFMT', 'R5T',
       'WAT', 'IRT', 'HMT', '+08', 'NZDT', '+0630', 'HWT', '+09', 'BGT',
       '+073', 'JMT', 'JDT', 'HKST', '+06', 'WMT'], dtype=object)

In [35]:
!pip install timezonefinder
!pip install swifter

Collecting timezonefinder
  Downloading timezonefinder-6.5.8-cp311-cp311-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: cffi<2,>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from timezonefinder) (1.17.1)
Collecting h3>4 (from timezonefinder)
  Downloading h3-4.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.11/dist-packages (from timezonefinder) (1.26.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi<2,>=1.15.1->timezonefinder) (2.22)
Downloading timezonefinder-6.5.8-cp311-cp311-manylinux_2_17_x86_64.manylinux_2_5_x86_64.manylinux1_x86_64.manylinux2014_x86_64.whl (51.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 MB 12.7 MB/s eta 0:00:00
Downloading h3-4.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 50.9 MB/s eta 0:00:00
Installing collected packages: h3, timezonefinder
Successfully installed h3-4.2.1 timezonefinder-6.5.8
Collecting swifter
  Downloading swifter-1.4.0.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from swifter) (2.2.2)
Requirement already satisfied: psutil>=5.6.6 in /usr/local/lib/python3.11/dist-packages (from swifter) (5.9.5)
Requirement already satisfied: dask>=2.10.0 in /usr/local/lib/python3.11/dist-packages (from dask[dataframe]>=2.10.0->swifter) (2024.10.0)
Requirement already satisfied: tqdm>=4.33.0 in /usr/local/lib/python3.11/dist-packages (from swifter) (4.67.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.1.8)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (2024.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (24.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.6.1)
Collecting dask-expr<1.2,>=1.1 (from dask[dataframe]>=2.10.0->swifter)
  Downloading dask_expr-1.1.21-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->swifter) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->swifter) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->swifter) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->swifter) (2025.1)
INFO: pip is looking at multiple versions of dask-expr to determine which version is compatible with other requirements. This could take a while.
  Downloading dask_expr-1.1.20-py3-none-any.whl.metadata (2.6 kB)
  Downloading dask_expr-1.1.19-py3-none-any.whl.metadata (2.6 kB)
  Downloading dask_expr-1.1.18-py3-none-any.whl.metadata (2.6 kB)
  Downloading dask_expr-1.1.16-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.11/dist-packages (from dask-expr<1.2,>=1.1->dask[dataframe]>=2.10.0->swifter) (17.0.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata>=4.13.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.21.0)
Requirement already satisfied: locket in /usr/local/lib/python3.11/dist-packages (from partd>=1.4.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->swifter) (1.17.0)
Downloading dask_expr-1.1.16-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 15.4 MB/s eta 0:00:00
Building wheels for collected packages: swifter
  Building wheel for swifter (setup.py) ... done
  Created wheel for swifter: filename=swifter-1.4.0-py3-none-any.whl size=16507 sha256=cefc9a13192d96c11ac892acac389d2ecdc80e7826858f0d9e0ab7b5eb2251b8
  Stored in directory: /root/.cache/pip/wheels/ef/7f/bd/9bed48f078f3ee1fa75e0b29b6e0335ce1cb03a38d3443b3a3
Successfully built swifter
Installing collected packages: dask-expr, swifter
Successfully installed dask-expr-1.1.16 swifter-1.4.0

In [36]:
# Determining timezone using longitude and latitude
from timezonefinder import TimezoneFinder
import swifter  # For faster pandas apply

tf = TimezoneFinder()

def get_Timezone(row):
    return tf.timezone_at(lng=row['longitude'], lat=row['latitude'])

df['UTC_Birth_Time_Zone'] = df.swifter.apply(get_Timezone, axis=1)

Pandas Apply:   0%|          | 0/6089 [00:00<?, ?it/s]

In [37]:
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,...,Career,Birth Place,lat_lon,get_latitude,get_longitude,latitude,longitude,Birth Date,Birth Time,UTC_Birth_Time_Zone
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,...,Entertain/Music,Provins France,"48n33, 3e18",48n33,3e18,48.55,3.30,6 October 1968,17:35,Europe/Paris
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,...,Entertain/Music,Lima Peru,"12s03, 77w03",12s03,77w03,-12.05,-77.05,30 May 1986,21:02,America/Lima
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,...,Writers,Tours France,"47n23, 0e41",47n23,0e41,47.38,0.68,19 December 1947,20:00,Europe/Paris
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,...,Business,Bryn Mawr (Delaware County) Pennsylvania,"40n0116, 75w1901",40n0116,75w1901,41.93,-106.68,28 September 1971,08:45,America/Denver
6,"ATL, Scotty",Walter Scott Williams,M,15 January 1985 at 08:25(= 08:25 AM ),"Atlanta, Georgia (US),33n45, 84w23",EST,From memory,A,Scholfield,25°21,...,Business,Atlanta Georgia (US),"33n45, 84w23",33n45,84w23,33.75,-84.38,15 January 1985,08:25,America/New_York

In [38]:
# remove rows with null 'Birth time'
df = df[df['Birth Time'].notnull()]

In [40]:
# Getting UTC time
import pandas as pd
from datetime import datetime
import pytz

def convert_to_utc(row):
    birth_datetime_str = f"{row['Birth Date']} {row['Birth Time']}"
    birth_datetime = datetime.strptime(birth_datetime_str, "%d %B %Y %H:%M")
    # print(birth_datetime)
    local_tz = pytz.timezone(row['UTC_Birth_Time_Zone'])
    # print(local_tz)
    local_time = local_tz.localize(birth_datetime)
    # Convert the local time to UTC
    utc_time = local_time.astimezone(pytz.utc)
    return utc_time.strftime("%H:%M")

df['UTC_Birth_Time'] = df.apply(convert_to_utc, axis=1)

# print(df1)

<ipython-input-40-a903cda93dc5>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['UTC_Birth_Time'] = df.apply(convert_to_utc, axis=1)

In [41]:
df.head()

,Name,Birthname,Gender,Date of Birth,Place of Birth,Timezone,Data Source,Rodden Rating,Collector,Sun Position,...,Birth Place,lat_lon,get_latitude,get_longitude,latitude,longitude,Birth Date,Birth Time,UTC_Birth_Time_Zone,UTC_Birth_Time
0,"A, Dominique",Dominique Ané,M,6 October 1968 at 17:35(= 5:35 PM ),"Provins, France,48n33, 3e18",MET,BC/BR in hand,AA,Geslain,13°29,...,Provins France,"48n33, 3e18",48n33,3e18,48.55,3.30,6 October 1968,17:35,Europe/Paris,16:35
2,A. Chal,Alejandro Salazar Pezo,M,30 May 1986 at 21:02(= 9:02 PM ),"Lima, Peru,12s03, 77w03",-05,BC/BR in hand,AA,Scholfield,09°21,...,Lima Peru,"12s03, 77w03",12s03,77w03,-12.05,-77.05,30 May 1986,21:02,America/Lima,02:02
3,A. D. G.,Alain Fournier,M,19 December 1947 at 20:00(= 8:00 PM ),"Tours, France,47n23, 0e41",MET,BC/BR in hand,AA,Geslain,27°03,...,Tours France,"47n23, 0e41",47n23,0e41,47.38,0.68,19 December 1947,20:00,Europe/Paris,19:00
4,A. J. Croce,Adrian James Croce,M,28 September 1971 at 08:45(= 08:45 AM ),"Bryn Mawr (Delaware County), Pennsylvania,40n0...",EDT,Bio/autobiography,B,Scholfield,04°44,...,Bryn Mawr (Delaware County) Pennsylvania,"40n0116, 75w1901",40n0116,75w1901,41.93,-106.68,28 September 1971,08:45,America/Denver,14:45
6,"ATL, Scotty",Walter Scott Williams,M,15 January 1985 at 08:25(= 08:25 AM ),"Atlanta, Georgia (US),33n45, 84w23",EST,From memory,A,Scholfield,25°21,...,Atlanta Georgia (US),"33n45, 84w23",33n45,84w23,33.75,-84.38,15 January 1985,08:25,America/New_York,13:25

In [42]:
df.columns

Index(['Name', 'Birthname', 'Gender', 'Date of Birth', 'Place of Birth',
       'Timezone', 'Data Source', 'Rodden Rating', 'Collector', 'Sun Position',
       'Moon Position', 'Asc pos', 'Career ', 'Birth Place', 'lat_lon',
       'get_latitude', 'get_longitude', 'latitude', 'longitude', 'Birth Date',
       'Birth Time', 'UTC_Birth_Time_Zone', 'UTC_Birth_Time'],
      dtype='object')

In [43]:
# Dropping columns that of no use
df.drop(columns=(['Date of Birth', 'Place of Birth','Timezone','lat_lon','get_latitude', 'get_longitude','Birthname']), inplace=True)

<ipython-input-43-61439aa4b5c6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=(['Date of Birth', 'Place of Birth','Timezone','lat_lon','get_latitude', 'get_longitude','Birthname']), inplace=True)

In [44]:
df.head()

,Name,Gender,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career,Birth Place,latitude,longitude,Birth Date,Birth Time,UTC_Birth_Time_Zone,UTC_Birth_Time
0,"A, Dominique",M,BC/BR in hand,AA,Geslain,13°29,15°48,24°32,Entertain/Music,Provins France,48.55,3.30,6 October 1968,17:35,Europe/Paris,16:35
2,A. Chal,M,BC/BR in hand,AA,Scholfield,09°21,15°55,24°34,Entertain/Music,Lima Peru,-12.05,-77.05,30 May 1986,21:02,America/Lima,02:02
3,A. D. G.,M,BC/BR in hand,AA,Geslain,27°03,16°28,03°25,Writers,Tours France,47.38,0.68,19 December 1947,20:00,Europe/Paris,19:00
4,A. J. Croce,M,Bio/autobiography,B,Scholfield,04°44,14°27,25°56,Business,Bryn Mawr (Delaware County) Pennsylvania,41.93,-106.68,28 September 1971,08:45,America/Denver,14:45
6,"ATL, Scotty",M,From memory,A,Scholfield,25°21,15°54,06°22,Business,Atlanta Georgia (US),33.75,-84.38,15 January 1985,08:25,America/New_York,13:25

In [45]:
df= df.rename(columns={'Career ':'Career'})

In [46]:
# Rearranging all column
df = df[['Name', 'Gender', 'Birth Date', 'Birth Time','Birth Place','latitude', 'longitude',
       'UTC_Birth_Time_Zone', 'UTC_Birth_Time','Data Source', 'Rodden Rating',
       'Collector', 'Sun Position', 'Moon Position', 'Asc pos', 'Career']]

In [47]:
# Reset the row index after filtering to ensure continuous numbering
df = df.reset_index(drop=True)

In [48]:
df.head()

,Name,Gender,Birth Date,Birth Time,Birth Place,latitude,longitude,UTC_Birth_Time_Zone,UTC_Birth_Time,Data Source,Rodden Rating,Collector,Sun Position,Moon Position,Asc pos,Career
0,"A, Dominique",M,6 October 1968,17:35,Provins France,48.55,3.30,Europe/Paris,16:35,BC/BR in hand,AA,Geslain,13°29,15°48,24°32,Entertain/Music
1,A. Chal,M,30 May 1986,21:02,Lima Peru,-12.05,-77.05,America/Lima,02:02,BC/BR in hand,AA,Scholfield,09°21,15°55,24°34,Entertain/Music
2,A. D. G.,M,19 December 1947,20:00,Tours France,47.38,0.68,Europe/Paris,19:00,BC/BR in hand,AA,Geslain,27°03,16°28,03°25,Writers
3,A. J. Croce,M,28 September 1971,08:45,Bryn Mawr (Delaware County) Pennsylvania,41.93,-106.68,America/Denver,14:45,Bio/autobiography,B,Scholfield,04°44,14°27,25°56,Business
4,"ATL, Scotty",M,15 January 1985,08:25,Atlanta Georgia (US),33.75,-84.38,America/New_York,13:25,From memory,A,Scholfield,25°21,15°54,06°22,Business

In [49]:
df.isnull().sum()

Name                     0
Gender                   0
Birth Date               0
Birth Time               0
Birth Place              0
latitude                 0
longitude                0
UTC_Birth_Time_Zone      0
UTC_Birth_Time           0
Data Source              0
Rodden Rating            0
Collector                0
Sun Position             0
Moon Position            0
Asc pos                  0
Career                 454
dtype: int64